# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\import_observation_form.ui'
#
# Created: Mon Apr 02 13:50:55 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_import_observation_form(object):
    def setupUi(self, import_observation_form):
        import_observation_form.setObjectName(_fromUtf8("import_observation_form"))
        import_observation_form.resize(791, 585)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(import_observation_form.sizePolicy().hasHeightForWidth())
        import_observation_form.setSizePolicy(sizePolicy)
        import_observation_form.setMinimumSize(QtCore.QSize(791, 585))
        import_observation_form.setMaximumSize(QtCore.QSize(791, 585))
        self.verticalLayout = QtGui.QVBoxLayout(import_observation_form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lbl_url_fichier = QtGui.QLabel(import_observation_form)
        self.lbl_url_fichier.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lbl_url_fichier.setStyleSheet(_fromUtf8("background-color: rgb(209, 223, 245);"))
        self.lbl_url_fichier.setText(_fromUtf8(""))
        self.lbl_url_fichier.setObjectName(_fromUtf8("lbl_url_fichier"))
        self.horizontalLayout_4.addWidget(self.lbl_url_fichier)
        self.btnSelectionFichier = QtGui.QPushButton(import_observation_form)
        self.btnSelectionFichier.setMinimumSize(QtCore.QSize(146, 30))
        self.btnSelectionFichier.setMaximumSize(QtCore.QSize(146, 16777215))
        self.btnSelectionFichier.setObjectName(_fromUtf8("btnSelectionFichier"))
        self.horizontalLayout_4.addWidget(self.btnSelectionFichier)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_15 = QtGui.QLabel(import_observation_form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout.addWidget(self.label_15)
        self.btnLancementEtape1 = QtGui.QPushButton(import_observation_form)
        self.btnLancementEtape1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLancementEtape1.sizePolicy().hasHeightForWidth())
        self.btnLancementEtape1.setSizePolicy(sizePolicy)
        self.btnLancementEtape1.setMinimumSize(QtCore.QSize(146, 30))
        self.btnLancementEtape1.setMaximumSize(QtCore.QSize(146, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geolimi/icons/import.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLancementEtape1.setIcon(icon)
        self.btnLancementEtape1.setObjectName(_fromUtf8("btnLancementEtape1"))
        self.horizontalLayout.addWidget(self.btnLancementEtape1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pbEtape1 = QtGui.QProgressBar(import_observation_form)
        self.pbEtape1.setProperty("value", 0)
        self.pbEtape1.setObjectName(_fromUtf8("pbEtape1"))
        self.verticalLayout.addWidget(self.pbEtape1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_21 = QtGui.QLabel(import_observation_form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_2.addWidget(self.label_21)
        self.btnLancementEtape2 = QtGui.QPushButton(import_observation_form)
        self.btnLancementEtape2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLancementEtape2.sizePolicy().hasHeightForWidth())
        self.btnLancementEtape2.setSizePolicy(sizePolicy)
        self.btnLancementEtape2.setMinimumSize(QtCore.QSize(146, 30))
        self.btnLancementEtape2.setMaximumSize(QtCore.QSize(146, 16777215))
        self.btnLancementEtape2.setIcon(icon)
        self.btnLancementEtape2.setObjectName(_fromUtf8("btnLancementEtape2"))
        self.horizontalLayout_2.addWidget(self.btnLancementEtape2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pbEtape2 = QtGui.QProgressBar(import_observation_form)
        self.pbEtape2.setProperty("value", 0)
        self.pbEtape2.setObjectName(_fromUtf8("pbEtape2"))
        self.verticalLayout.addWidget(self.pbEtape2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lbl_url_goeland = QtGui.QLabel(import_observation_form)
        self.lbl_url_goeland.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lbl_url_goeland.setStyleSheet(_fromUtf8("background-color: rgb(209, 223, 245);"))
        self.lbl_url_goeland.setText(_fromUtf8(""))
        self.lbl_url_goeland.setObjectName(_fromUtf8("lbl_url_goeland"))
        self.horizontalLayout_5.addWidget(self.lbl_url_goeland)
        self.btnSelectionGoel = QtGui.QPushButton(import_observation_form)
        self.btnSelectionGoel.setMinimumSize(QtCore.QSize(146, 30))
        self.btnSelectionGoel.setMaximumSize(QtCore.QSize(146, 16777215))
        self.btnSelectionGoel.setObjectName(_fromUtf8("btnSelectionGoel"))
        self.horizontalLayout_5.addWidget(self.btnSelectionGoel)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_27 = QtGui.QLabel(import_observation_form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_3.addWidget(self.label_27)
        self.btnLancementEtape3 = QtGui.QPushButton(import_observation_form)
        self.btnLancementEtape3.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLancementEtape3.sizePolicy().hasHeightForWidth())
        self.btnLancementEtape3.setSizePolicy(sizePolicy)
        self.btnLancementEtape3.setMinimumSize(QtCore.QSize(146, 30))
        self.btnLancementEtape3.setMaximumSize(QtCore.QSize(146, 16777215))
        self.btnLancementEtape3.setIcon(icon)
        self.btnLancementEtape3.setObjectName(_fromUtf8("btnLancementEtape3"))
        self.horizontalLayout_3.addWidget(self.btnLancementEtape3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.pbEtape3 = QtGui.QProgressBar(import_observation_form)
        self.pbEtape3.setProperty("value", 0)
        self.pbEtape3.setObjectName(_fromUtf8("pbEtape3"))
        self.verticalLayout.addWidget(self.pbEtape3)
        self.btnQuitter = QtGui.QPushButton(import_observation_form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnQuitter.sizePolicy().hasHeightForWidth())
        self.btnQuitter.setSizePolicy(sizePolicy)
        self.btnQuitter.setMinimumSize(QtCore.QSize(75, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geolimi/icons/quit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnQuitter.setIcon(icon1)
        self.btnQuitter.setObjectName(_fromUtf8("btnQuitter"))
        self.verticalLayout.addWidget(self.btnQuitter)

        self.retranslateUi(import_observation_form)
        QtCore.QMetaObject.connectSlotsByName(import_observation_form)

    def retranslateUi(self, import_observation_form):
        import_observation_form.setWindowTitle(_translate("import_observation_form", "Geolimi - Import d\'observations", None))
        self.btnSelectionFichier.setToolTip(_translate("import_observation_form", "Sélectionner le fichier à insérer", None))
        self.btnSelectionFichier.setText(_translate("import_observation_form", "Sélectionner un fichier", None))
        self.label_15.setText(_translate("import_observation_form", "Etape 1 : quantification des données à importer", None))
        self.btnLancementEtape1.setToolTip(_translate("import_observation_form", "Parcourir le contenu du fichier", None))
        self.btnLancementEtape1.setText(_translate("import_observation_form", "Lancement étape 1", None))
        self.label_21.setText(_translate("import_observation_form", "Etape 2 : vérification des données à importer", None))
        self.btnLancementEtape2.setToolTip(_translate("import_observation_form", "Vérifier les données du fichier", None))
        self.btnLancementEtape2.setText(_translate("import_observation_form", "Lancement étape 2", None))
        self.btnSelectionGoel.setToolTip(_translate("import_observation_form", "Sélectionner le fichier à insérer", None))
        self.btnSelectionGoel.setText(_translate("import_observation_form", "Sélectionner un fichier", None))
        self.label_27.setText(_translate("import_observation_form", "Etape 3 : import", None))
        self.btnLancementEtape3.setToolTip(_translate("import_observation_form", "Insertion des données dans la base", None))
        self.btnLancementEtape3.setText(_translate("import_observation_form", "Lancement étape 3", None))
        self.btnQuitter.setText(_translate("import_observation_form", "Quitter", None))

import resourcesGeolimi_rc
