# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\import_lune_form.ui'
#
# Created: Mon Apr 02 13:50:53 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_import_lune_form(object):
    def setupUi(self, import_lune_form):
        import_lune_form.setObjectName(_fromUtf8("import_lune_form"))
        import_lune_form.resize(791, 585)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(import_lune_form.sizePolicy().hasHeightForWidth())
        import_lune_form.setSizePolicy(sizePolicy)
        import_lune_form.setMinimumSize(QtCore.QSize(791, 585))
        import_lune_form.setMaximumSize(QtCore.QSize(791, 585))
        self.verticalLayout_2 = QtGui.QVBoxLayout(import_lune_form)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lbl_url_fichier = QtGui.QLabel(import_lune_form)
        self.lbl_url_fichier.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lbl_url_fichier.setStyleSheet(_fromUtf8("background-color: rgb(209, 223, 245);"))
        self.lbl_url_fichier.setText(_fromUtf8(""))
        self.lbl_url_fichier.setObjectName(_fromUtf8("lbl_url_fichier"))
        self.horizontalLayout_3.addWidget(self.lbl_url_fichier)
        self.btnSelectionFichier = QtGui.QPushButton(import_lune_form)
        self.btnSelectionFichier.setMinimumSize(QtCore.QSize(146, 30))
        self.btnSelectionFichier.setMaximumSize(QtCore.QSize(146, 16777215))
        self.btnSelectionFichier.setObjectName(_fromUtf8("btnSelectionFichier"))
        self.horizontalLayout_3.addWidget(self.btnSelectionFichier)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_15 = QtGui.QLabel(import_lune_form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_4.addWidget(self.label_15)
        self.btnLancementEtape1 = QtGui.QPushButton(import_lune_form)
        self.btnLancementEtape1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLancementEtape1.sizePolicy().hasHeightForWidth())
        self.btnLancementEtape1.setSizePolicy(sizePolicy)
        self.btnLancementEtape1.setMinimumSize(QtCore.QSize(146, 30))
        self.btnLancementEtape1.setMaximumSize(QtCore.QSize(146, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geolimi/icons/import.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLancementEtape1.setIcon(icon)
        self.btnLancementEtape1.setObjectName(_fromUtf8("btnLancementEtape1"))
        self.horizontalLayout_4.addWidget(self.btnLancementEtape1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.pbEtape1 = QtGui.QProgressBar(import_lune_form)
        self.pbEtape1.setProperty("value", 0)
        self.pbEtape1.setObjectName(_fromUtf8("pbEtape1"))
        self.verticalLayout.addWidget(self.pbEtape1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_21 = QtGui.QLabel(import_lune_form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_2.addWidget(self.label_21)
        self.btnLancementEtape2 = QtGui.QPushButton(import_lune_form)
        self.btnLancementEtape2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLancementEtape2.sizePolicy().hasHeightForWidth())
        self.btnLancementEtape2.setSizePolicy(sizePolicy)
        self.btnLancementEtape2.setMinimumSize(QtCore.QSize(146, 30))
        self.btnLancementEtape2.setMaximumSize(QtCore.QSize(146, 16777215))
        self.btnLancementEtape2.setIcon(icon)
        self.btnLancementEtape2.setObjectName(_fromUtf8("btnLancementEtape2"))
        self.horizontalLayout_2.addWidget(self.btnLancementEtape2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pbEtape2 = QtGui.QProgressBar(import_lune_form)
        self.pbEtape2.setProperty("value", 0)
        self.pbEtape2.setObjectName(_fromUtf8("pbEtape2"))
        self.verticalLayout.addWidget(self.pbEtape2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_27 = QtGui.QLabel(import_lune_form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout.addWidget(self.label_27)
        self.btnLancementEtape3 = QtGui.QPushButton(import_lune_form)
        self.btnLancementEtape3.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLancementEtape3.sizePolicy().hasHeightForWidth())
        self.btnLancementEtape3.setSizePolicy(sizePolicy)
        self.btnLancementEtape3.setMinimumSize(QtCore.QSize(146, 30))
        self.btnLancementEtape3.setMaximumSize(QtCore.QSize(146, 16777215))
        self.btnLancementEtape3.setIcon(icon)
        self.btnLancementEtape3.setObjectName(_fromUtf8("btnLancementEtape3"))
        self.horizontalLayout.addWidget(self.btnLancementEtape3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pbEtape3 = QtGui.QProgressBar(import_lune_form)
        self.pbEtape3.setProperty("value", 0)
        self.pbEtape3.setObjectName(_fromUtf8("pbEtape3"))
        self.verticalLayout.addWidget(self.pbEtape3)
        self.btnQuitter = QtGui.QPushButton(import_lune_form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnQuitter.sizePolicy().hasHeightForWidth())
        self.btnQuitter.setSizePolicy(sizePolicy)
        self.btnQuitter.setMinimumSize(QtCore.QSize(75, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geolimi/icons/quit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnQuitter.setIcon(icon1)
        self.btnQuitter.setObjectName(_fromUtf8("btnQuitter"))
        self.verticalLayout.addWidget(self.btnQuitter)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(import_lune_form)
        QtCore.QMetaObject.connectSlotsByName(import_lune_form)

    def retranslateUi(self, import_lune_form):
        import_lune_form.setWindowTitle(_translate("import_lune_form", "Geolimi - Import de lunes", None))
        self.btnSelectionFichier.setToolTip(_translate("import_lune_form", "Sélectionner le fichier", None))
        self.btnSelectionFichier.setText(_translate("import_lune_form", "Sélectionner un fichier", None))
        self.label_15.setText(_translate("import_lune_form", "Etape 1 : quantification des données à importer", None))
        self.btnLancementEtape1.setToolTip(_translate("import_lune_form", "Parcourir le fichier", None))
        self.btnLancementEtape1.setText(_translate("import_lune_form", "Lancement étape 1", None))
        self.label_21.setText(_translate("import_lune_form", "Etape 2 : vérification des données à importer", None))
        self.btnLancementEtape2.setToolTip(_translate("import_lune_form", "Vérifier le contenu du fichier", None))
        self.btnLancementEtape2.setText(_translate("import_lune_form", "Lancement étape 2", None))
        self.label_27.setText(_translate("import_lune_form", "Etape 3 : import", None))
        self.btnLancementEtape3.setToolTip(_translate("import_lune_form", "Insérer le contenu dans la base", None))
        self.btnLancementEtape3.setText(_translate("import_lune_form", "Lancement étape 3", None))
        self.btnQuitter.setText(_translate("import_lune_form", "Quitter", None))

import resourcesGeolimi_rc
