# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\individu_form.ui'
#
# Created: Mon Apr 02 13:50:57 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_individu_form(object):
    def setupUi(self, individu_form):
        individu_form.setObjectName(_fromUtf8("individu_form"))
        individu_form.resize(485, 737)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(individu_form.sizePolicy().hasHeightForWidth())
        individu_form.setSizePolicy(sizePolicy)
        individu_form.setMinimumSize(QtCore.QSize(485, 737))
        individu_form.setStyleSheet(_fromUtf8(""))
        self.dwc_individu = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwc_individu.sizePolicy().hasHeightForWidth())
        self.dwc_individu.setSizePolicy(sizePolicy)
        self.dwc_individu.setMinimumSize(QtCore.QSize(485, 715))
        self.dwc_individu.setStyleSheet(_fromUtf8(""))
        self.dwc_individu.setObjectName(_fromUtf8("dwc_individu"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dwc_individu)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setMargin(2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkFiltreIndividu = QtGui.QCheckBox(self.dwc_individu)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFiltreIndividu.sizePolicy().hasHeightForWidth())
        self.chkFiltreIndividu.setSizePolicy(sizePolicy)
        self.chkFiltreIndividu.setMinimumSize(QtCore.QSize(85, 0))
        self.chkFiltreIndividu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setItalic(False)
        self.chkFiltreIndividu.setFont(font)
        self.chkFiltreIndividu.setChecked(False)
        self.chkFiltreIndividu.setObjectName(_fromUtf8("chkFiltreIndividu"))
        self.horizontalLayout.addWidget(self.chkFiltreIndividu)
        self.btnFiltreAttributaire = QtGui.QPushButton(self.dwc_individu)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFiltreAttributaire.sizePolicy().hasHeightForWidth())
        self.btnFiltreAttributaire.setSizePolicy(sizePolicy)
        self.btnFiltreAttributaire.setMinimumSize(QtCore.QSize(90, 30))
        self.btnFiltreAttributaire.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnFiltreAttributaire.setObjectName(_fromUtf8("btnFiltreAttributaire"))
        self.horizontalLayout.addWidget(self.btnFiltreAttributaire)
        self.btnDeleteFiltrage = QtGui.QPushButton(self.dwc_individu)
        self.btnDeleteFiltrage.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeleteFiltrage.sizePolicy().hasHeightForWidth())
        self.btnDeleteFiltrage.setSizePolicy(sizePolicy)
        self.btnDeleteFiltrage.setMinimumSize(QtCore.QSize(105, 30))
        self.btnDeleteFiltrage.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnDeleteFiltrage.setObjectName(_fromUtf8("btnDeleteFiltrage"))
        self.horizontalLayout.addWidget(self.btnDeleteFiltrage)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.frame = QtGui.QFrame(self.dwc_individu)
        self.frame.setStyleSheet(_fromUtf8("background-color: rgb(209, 223, 245);"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setContentsMargins(35, -1, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet(_fromUtf8("color: rgb(107, 107, 107);"))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.le_ind_id = QtGui.QLineEdit(self.frame)
        self.le_ind_id.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_ind_id.sizePolicy().hasHeightForWidth())
        self.le_ind_id.setSizePolicy(sizePolicy)
        self.le_ind_id.setMinimumSize(QtCore.QSize(50, 0))
        self.le_ind_id.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.le_ind_id.setFont(font)
        self.le_ind_id.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);background-color: rgb(255, 255, 255);"))
        self.le_ind_id.setText(_fromUtf8(""))
        self.le_ind_id.setAlignment(QtCore.Qt.AlignCenter)
        self.le_ind_id.setObjectName(_fromUtf8("le_ind_id"))
        self.horizontalLayout_2.addWidget(self.le_ind_id)
        self.chk_ind_actif = QtGui.QCheckBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chk_ind_actif.sizePolicy().hasHeightForWidth())
        self.chk_ind_actif.setSizePolicy(sizePolicy)
        self.chk_ind_actif.setMinimumSize(QtCore.QSize(0, 20))
        self.chk_ind_actif.setStyleSheet(_fromUtf8("color: rgb(107, 107, 107);"))
        self.chk_ind_actif.setObjectName(_fromUtf8("chk_ind_actif"))
        self.horizontalLayout_2.addWidget(self.chk_ind_actif)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet(_fromUtf8("color: rgb(107, 107, 107);"))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.le_ind_log = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_ind_log.sizePolicy().hasHeightForWidth())
        self.le_ind_log.setSizePolicy(sizePolicy)
        self.le_ind_log.setMinimumSize(QtCore.QSize(40, 0))
        self.le_ind_log.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le_ind_log.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.le_ind_log.setText(_fromUtf8(""))
        self.le_ind_log.setAlignment(QtCore.Qt.AlignCenter)
        self.le_ind_log.setObjectName(_fromUtf8("le_ind_log"))
        self.horizontalLayout_2.addWidget(self.le_ind_log)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setStyleSheet(_fromUtf8("color: rgb(107, 107, 107);"))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        self.cmb_ind_esp_id = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_ind_esp_id.sizePolicy().hasHeightForWidth())
        self.cmb_ind_esp_id.setSizePolicy(sizePolicy)
        self.cmb_ind_esp_id.setMinimumSize(QtCore.QSize(76, 20))
        self.cmb_ind_esp_id.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.cmb_ind_esp_id.setObjectName(_fromUtf8("cmb_ind_esp_id"))
        self.horizontalLayout_3.addWidget(self.cmb_ind_esp_id)
        self.btnGereEspece = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGereEspece.sizePolicy().hasHeightForWidth())
        self.btnGereEspece.setSizePolicy(sizePolicy)
        self.btnGereEspece.setMinimumSize(QtCore.QSize(31, 20))
        self.btnGereEspece.setMaximumSize(QtCore.QSize(31, 20))
        self.btnGereEspece.setObjectName(_fromUtf8("btnGereEspece"))
        self.horizontalLayout_3.addWidget(self.btnGereEspece)
        spacerItem1 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(26, -1, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setStyleSheet(_fromUtf8("color: rgb(107, 107, 107);"))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.cmb_ind_age_id = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_ind_age_id.sizePolicy().hasHeightForWidth())
        self.cmb_ind_age_id.setSizePolicy(sizePolicy)
        self.cmb_ind_age_id.setMinimumSize(QtCore.QSize(161, 20))
        self.cmb_ind_age_id.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.cmb_ind_age_id.setObjectName(_fromUtf8("cmb_ind_age_id"))
        self.horizontalLayout_4.addWidget(self.cmb_ind_age_id)
        self.btnGereAge = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGereAge.sizePolicy().hasHeightForWidth())
        self.btnGereAge.setSizePolicy(sizePolicy)
        self.btnGereAge.setMinimumSize(QtCore.QSize(31, 20))
        self.btnGereAge.setMaximumSize(QtCore.QSize(31, 20))
        self.btnGereAge.setObjectName(_fromUtf8("btnGereAge"))
        self.horizontalLayout_4.addWidget(self.btnGereAge)
        spacerItem2 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.chk_ind_sexe_m = QtGui.QCheckBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chk_ind_sexe_m.sizePolicy().hasHeightForWidth())
        self.chk_ind_sexe_m.setSizePolicy(sizePolicy)
        self.chk_ind_sexe_m.setMinimumSize(QtCore.QSize(0, 20))
        self.chk_ind_sexe_m.setStyleSheet(_fromUtf8("color: rgb(107, 107, 107);"))
        self.chk_ind_sexe_m.setObjectName(_fromUtf8("chk_ind_sexe_m"))
        self.horizontalLayout_4.addWidget(self.chk_ind_sexe_m)
        self.chk_ind_sexe_verifie = QtGui.QCheckBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chk_ind_sexe_verifie.sizePolicy().hasHeightForWidth())
        self.chk_ind_sexe_verifie.setSizePolicy(sizePolicy)
        self.chk_ind_sexe_verifie.setMinimumSize(QtCore.QSize(0, 20))
        self.chk_ind_sexe_verifie.setStyleSheet(_fromUtf8("color: rgb(107, 107, 107);"))
        self.chk_ind_sexe_verifie.setObjectName(_fromUtf8("chk_ind_sexe_verifie"))
        self.horizontalLayout_4.addWidget(self.chk_ind_sexe_verifie)
        spacerItem3 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(12, -1, -1, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setStyleSheet(_fromUtf8("color: rgb(107, 107, 107);"))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_5.addWidget(self.label_10)
        self.cmb_ind_distr_id = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_ind_distr_id.sizePolicy().hasHeightForWidth())
        self.cmb_ind_distr_id.setSizePolicy(sizePolicy)
        self.cmb_ind_distr_id.setMinimumSize(QtCore.QSize(76, 20))
        self.cmb_ind_distr_id.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.cmb_ind_distr_id.setObjectName(_fromUtf8("cmb_ind_distr_id"))
        self.horizontalLayout_5.addWidget(self.cmb_ind_distr_id)
        self.btnGereDistrict = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGereDistrict.sizePolicy().hasHeightForWidth())
        self.btnGereDistrict.setSizePolicy(sizePolicy)
        self.btnGereDistrict.setMinimumSize(QtCore.QSize(31, 20))
        self.btnGereDistrict.setMaximumSize(QtCore.QSize(31, 20))
        self.btnGereDistrict.setObjectName(_fromUtf8("btnGereDistrict"))
        self.horizontalLayout_5.addWidget(self.btnGereDistrict)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet(_fromUtf8("color: rgb(107, 107, 107);"))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.de_ind_date_capt = QtGui.QDateEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.de_ind_date_capt.sizePolicy().hasHeightForWidth())
        self.de_ind_date_capt.setSizePolicy(sizePolicy)
        self.de_ind_date_capt.setMinimumSize(QtCore.QSize(85, 20))
        self.de_ind_date_capt.setCalendarPopup(True)
        self.de_ind_date_capt.setObjectName(_fromUtf8("de_ind_date_capt"))
        self.horizontalLayout_5.addWidget(self.de_ind_date_capt)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet(_fromUtf8("color: rgb(107, 107, 107);"))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.le_ind_no_bague = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_ind_no_bague.sizePolicy().hasHeightForWidth())
        self.le_ind_no_bague.setSizePolicy(sizePolicy)
        self.le_ind_no_bague.setMinimumSize(QtCore.QSize(220, 0))
        self.le_ind_no_bague.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le_ind_no_bague.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.le_ind_no_bague.setText(_fromUtf8(""))
        self.le_ind_no_bague.setObjectName(_fromUtf8("le_ind_no_bague"))
        self.horizontalLayout_6.addWidget(self.le_ind_no_bague)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(0, -1, 10, -1)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setStyleSheet(_fromUtf8("color: rgb(107, 107, 107);"))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_12.addWidget(self.label_11)
        self.le_ind_code_gauche = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_ind_code_gauche.sizePolicy().hasHeightForWidth())
        self.le_ind_code_gauche.setSizePolicy(sizePolicy)
        self.le_ind_code_gauche.setMinimumSize(QtCore.QSize(150, 0))
        self.le_ind_code_gauche.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.le_ind_code_gauche.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.le_ind_code_gauche.setText(_fromUtf8(""))
        self.le_ind_code_gauche.setObjectName(_fromUtf8("le_ind_code_gauche"))
        self.horizontalLayout_12.addWidget(self.le_ind_code_gauche)
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setStyleSheet(_fromUtf8("color: rgb(107, 107, 107);"))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_12.addWidget(self.label_12)
        self.le_ind_code_droit = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_ind_code_droit.sizePolicy().hasHeightForWidth())
        self.le_ind_code_droit.setSizePolicy(sizePolicy)
        self.le_ind_code_droit.setMinimumSize(QtCore.QSize(150, 0))
        self.le_ind_code_droit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.le_ind_code_droit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.le_ind_code_droit.setText(_fromUtf8(""))
        self.le_ind_code_droit.setObjectName(_fromUtf8("le_ind_code_droit"))
        self.horizontalLayout_12.addWidget(self.le_ind_code_droit)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.verticalLayout_6.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.dwc_individu)
        self.frame_2.setStyleSheet(_fromUtf8("background-color: rgb(209, 223, 245);"))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setContentsMargins(-1, 2, -1, 5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_18 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_18.setFont(font)
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setStyleSheet(_fromUtf8("color: rgb(165, 165, 165);"))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_2.addWidget(self.label_18)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_25 = QtGui.QLabel(self.frame_2)
        self.label_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_25.setStyleSheet(_fromUtf8("color: rgb(107, 107, 107);"))
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_13.addWidget(self.label_25)
        self.le_ind_aile = QtGui.QLineEdit(self.frame_2)
        self.le_ind_aile.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_ind_aile.sizePolicy().hasHeightForWidth())
        self.le_ind_aile.setSizePolicy(sizePolicy)
        self.le_ind_aile.setMinimumSize(QtCore.QSize(30, 20))
        self.le_ind_aile.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le_ind_aile.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.le_ind_aile.setText(_fromUtf8(""))
        self.le_ind_aile.setAlignment(QtCore.Qt.AlignCenter)
        self.le_ind_aile.setObjectName(_fromUtf8("le_ind_aile"))
        self.horizontalLayout_13.addWidget(self.le_ind_aile)
        self.label_26 = QtGui.QLabel(self.frame_2)
        self.label_26.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_26.setStyleSheet(_fromUtf8("color: rgb(107, 107, 107);"))
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_13.addWidget(self.label_26)
        self.le_ind_bec = QtGui.QLineEdit(self.frame_2)
        self.le_ind_bec.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_ind_bec.sizePolicy().hasHeightForWidth())
        self.le_ind_bec.setSizePolicy(sizePolicy)
        self.le_ind_bec.setMinimumSize(QtCore.QSize(30, 20))
        self.le_ind_bec.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le_ind_bec.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.le_ind_bec.setText(_fromUtf8(""))
        self.le_ind_bec.setAlignment(QtCore.Qt.AlignCenter)
        self.le_ind_bec.setObjectName(_fromUtf8("le_ind_bec"))
        self.horizontalLayout_13.addWidget(self.le_ind_bec)
        self.label_27 = QtGui.QLabel(self.frame_2)
        self.label_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_27.setStyleSheet(_fromUtf8("color: rgb(107, 107, 107);"))
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_13.addWidget(self.label_27)
        self.le_ind_tarse = QtGui.QLineEdit(self.frame_2)
        self.le_ind_tarse.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_ind_tarse.sizePolicy().hasHeightForWidth())
        self.le_ind_tarse.setSizePolicy(sizePolicy)
        self.le_ind_tarse.setMinimumSize(QtCore.QSize(30, 20))
        self.le_ind_tarse.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le_ind_tarse.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.le_ind_tarse.setText(_fromUtf8(""))
        self.le_ind_tarse.setAlignment(QtCore.Qt.AlignCenter)
        self.le_ind_tarse.setObjectName(_fromUtf8("le_ind_tarse"))
        self.horizontalLayout_13.addWidget(self.le_ind_tarse)
        self.label_28 = QtGui.QLabel(self.frame_2)
        self.label_28.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_28.setStyleSheet(_fromUtf8("color: rgb(107, 107, 107);"))
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_13.addWidget(self.label_28)
        self.le_ind_masse = QtGui.QLineEdit(self.frame_2)
        self.le_ind_masse.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_ind_masse.sizePolicy().hasHeightForWidth())
        self.le_ind_masse.setSizePolicy(sizePolicy)
        self.le_ind_masse.setMinimumSize(QtCore.QSize(30, 20))
        self.le_ind_masse.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le_ind_masse.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.le_ind_masse.setText(_fromUtf8(""))
        self.le_ind_masse.setAlignment(QtCore.Qt.AlignCenter)
        self.le_ind_masse.setObjectName(_fromUtf8("le_ind_masse"))
        self.horizontalLayout_13.addWidget(self.le_ind_masse)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.tab_infos = QtGui.QTabWidget(self.dwc_individu)
        self.tab_infos.setStyleSheet(_fromUtf8("background-color: rgb(234, 234, 234);"))
        self.tab_infos.setObjectName(_fromUtf8("tab_infos"))
        self.tab_observation = QtGui.QWidget()
        self.tab_observation.setObjectName(_fromUtf8("tab_observation"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_observation)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem5 = QtGui.QSpacerItem(350, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem5)
        self.btnAddObservation = QtGui.QPushButton(self.tab_observation)
        self.btnAddObservation.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddObservation.sizePolicy().hasHeightForWidth())
        self.btnAddObservation.setSizePolicy(sizePolicy)
        self.btnAddObservation.setMinimumSize(QtCore.QSize(25, 25))
        self.btnAddObservation.setMaximumSize(QtCore.QSize(25, 25))
        self.btnAddObservation.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geolimi/icons/list-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddObservation.setIcon(icon)
        self.btnAddObservation.setObjectName(_fromUtf8("btnAddObservation"))
        self.horizontalLayout_17.addWidget(self.btnAddObservation)
        self.btnDeleteObservation = QtGui.QPushButton(self.tab_observation)
        self.btnDeleteObservation.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeleteObservation.sizePolicy().hasHeightForWidth())
        self.btnDeleteObservation.setSizePolicy(sizePolicy)
        self.btnDeleteObservation.setMinimumSize(QtCore.QSize(25, 25))
        self.btnDeleteObservation.setMaximumSize(QtCore.QSize(25, 25))
        self.btnDeleteObservation.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geolimi/icons/list-remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDeleteObservation.setIcon(icon1)
        self.btnDeleteObservation.setObjectName(_fromUtf8("btnDeleteObservation"))
        self.horizontalLayout_17.addWidget(self.btnDeleteObservation)
        self.btnEditObservation = QtGui.QPushButton(self.tab_observation)
        self.btnEditObservation.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEditObservation.sizePolicy().hasHeightForWidth())
        self.btnEditObservation.setSizePolicy(sizePolicy)
        self.btnEditObservation.setMinimumSize(QtCore.QSize(50, 25))
        self.btnEditObservation.setMaximumSize(QtCore.QSize(25, 25))
        self.btnEditObservation.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geolimi/icons/edition.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEditObservation.setIcon(icon2)
        self.btnEditObservation.setObjectName(_fromUtf8("btnEditObservation"))
        self.horizontalLayout_17.addWidget(self.btnEditObservation)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.tv_observation = QtGui.QTableView(self.tab_observation)
        self.tv_observation.setStyleSheet(_fromUtf8("background-color: rgb(239, 244, 251);"))
        self.tv_observation.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tv_observation.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tv_observation.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tv_observation.setObjectName(_fromUtf8("tv_observation"))
        self.verticalLayout_3.addWidget(self.tv_observation)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(0, -1, 0, 5)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.btnCentrer = QtGui.QPushButton(self.tab_observation)
        self.btnCentrer.setEnabled(True)
        self.btnCentrer.setMinimumSize(QtCore.QSize(0, 36))
        self.btnCentrer.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geolimi/icons/centrer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCentrer.setIcon(icon3)
        self.btnCentrer.setObjectName(_fromUtf8("btnCentrer"))
        self.horizontalLayout_11.addWidget(self.btnCentrer)
        self.btnZoomer = QtGui.QPushButton(self.tab_observation)
        self.btnZoomer.setEnabled(True)
        self.btnZoomer.setMinimumSize(QtCore.QSize(0, 36))
        self.btnZoomer.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geolimi/icons/zoom.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnZoomer.setIcon(icon4)
        self.btnZoomer.setObjectName(_fromUtf8("btnZoomer"))
        self.horizontalLayout_11.addWidget(self.btnZoomer)
        self.btnSelectionner = QtGui.QPushButton(self.tab_observation)
        self.btnSelectionner.setEnabled(True)
        self.btnSelectionner.setMinimumSize(QtCore.QSize(0, 36))
        self.btnSelectionner.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geolimi/icons/select.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSelectionner.setIcon(icon5)
        self.btnSelectionner.setObjectName(_fromUtf8("btnSelectionner"))
        self.horizontalLayout_11.addWidget(self.btnSelectionner)
        self.btnZoomerSelectionner = QtGui.QPushButton(self.tab_observation)
        self.btnZoomerSelectionner.setEnabled(True)
        self.btnZoomerSelectionner.setMinimumSize(QtCore.QSize(0, 36))
        self.btnZoomerSelectionner.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geolimi/icons/zoom_select.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnZoomerSelectionner.setIcon(icon6)
        self.btnZoomerSelectionner.setIconSize(QtCore.QSize(32, 16))
        self.btnZoomerSelectionner.setObjectName(_fromUtf8("btnZoomerSelectionner"))
        self.horizontalLayout_11.addWidget(self.btnZoomerSelectionner)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.tab_infos.addTab(self.tab_observation, _fromUtf8(""))
        self.tab_logger = QtGui.QWidget()
        self.tab_logger.setObjectName(_fromUtf8("tab_logger"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_logger)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        spacerItem6 = QtGui.QSpacerItem(350, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem6)
        self.btnAddAncienLogger = QtGui.QPushButton(self.tab_logger)
        self.btnAddAncienLogger.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddAncienLogger.sizePolicy().hasHeightForWidth())
        self.btnAddAncienLogger.setSizePolicy(sizePolicy)
        self.btnAddAncienLogger.setMinimumSize(QtCore.QSize(25, 25))
        self.btnAddAncienLogger.setMaximumSize(QtCore.QSize(25, 25))
        self.btnAddAncienLogger.setText(_fromUtf8(""))
        self.btnAddAncienLogger.setIcon(icon)
        self.btnAddAncienLogger.setObjectName(_fromUtf8("btnAddAncienLogger"))
        self.horizontalLayout_19.addWidget(self.btnAddAncienLogger)
        self.btnDeleteAncienLogger = QtGui.QPushButton(self.tab_logger)
        self.btnDeleteAncienLogger.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeleteAncienLogger.sizePolicy().hasHeightForWidth())
        self.btnDeleteAncienLogger.setSizePolicy(sizePolicy)
        self.btnDeleteAncienLogger.setMinimumSize(QtCore.QSize(25, 25))
        self.btnDeleteAncienLogger.setMaximumSize(QtCore.QSize(25, 25))
        self.btnDeleteAncienLogger.setText(_fromUtf8(""))
        self.btnDeleteAncienLogger.setIcon(icon1)
        self.btnDeleteAncienLogger.setObjectName(_fromUtf8("btnDeleteAncienLogger"))
        self.horizontalLayout_19.addWidget(self.btnDeleteAncienLogger)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.tv_ancien_logger = QtGui.QTableView(self.tab_logger)
        self.tv_ancien_logger.setStyleSheet(_fromUtf8("background-color: rgb(230, 238, 214);"))
        self.tv_ancien_logger.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tv_ancien_logger.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tv_ancien_logger.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tv_ancien_logger.setObjectName(_fromUtf8("tv_ancien_logger"))
        self.verticalLayout_5.addWidget(self.tv_ancien_logger)
        self.tab_infos.addTab(self.tab_logger, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.tab_infos)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(2)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.btnFirst = QtGui.QPushButton(self.dwc_individu)
        self.btnFirst.setMinimumSize(QtCore.QSize(50, 30))
        self.btnFirst.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geolimi/icons/first.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFirst.setIcon(icon7)
        self.btnFirst.setIconSize(QtCore.QSize(25, 25))
        self.btnFirst.setObjectName(_fromUtf8("btnFirst"))
        self.horizontalLayout_14.addWidget(self.btnFirst)
        self.btnPrev = QtGui.QPushButton(self.dwc_individu)
        self.btnPrev.setMinimumSize(QtCore.QSize(50, 30))
        self.btnPrev.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geolimi/icons/prev.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrev.setIcon(icon8)
        self.btnPrev.setIconSize(QtCore.QSize(25, 25))
        self.btnPrev.setObjectName(_fromUtf8("btnPrev"))
        self.horizontalLayout_14.addWidget(self.btnPrev)
        self.btnNext = QtGui.QPushButton(self.dwc_individu)
        self.btnNext.setMinimumSize(QtCore.QSize(50, 30))
        self.btnNext.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geolimi/icons/next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNext.setIcon(icon9)
        self.btnNext.setIconSize(QtCore.QSize(25, 25))
        self.btnNext.setObjectName(_fromUtf8("btnNext"))
        self.horizontalLayout_14.addWidget(self.btnNext)
        self.btnLast = QtGui.QPushButton(self.dwc_individu)
        self.btnLast.setMinimumSize(QtCore.QSize(50, 30))
        self.btnLast.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geolimi/icons/last.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLast.setIcon(icon10)
        self.btnLast.setIconSize(QtCore.QSize(25, 25))
        self.btnLast.setObjectName(_fromUtf8("btnLast"))
        self.horizontalLayout_14.addWidget(self.btnLast)
        self.btnAdd = QtGui.QPushButton(self.dwc_individu)
        self.btnAdd.setMinimumSize(QtCore.QSize(65, 30))
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.horizontalLayout_14.addWidget(self.btnAdd)
        self.btnDelete = QtGui.QPushButton(self.dwc_individu)
        self.btnDelete.setEnabled(False)
        self.btnDelete.setMinimumSize(QtCore.QSize(65, 30))
        self.btnDelete.setObjectName(_fromUtf8("btnDelete"))
        self.horizontalLayout_14.addWidget(self.btnDelete)
        self.btnValidate = QtGui.QPushButton(self.dwc_individu)
        self.btnValidate.setEnabled(False)
        self.btnValidate.setMinimumSize(QtCore.QSize(60, 30))
        self.btnValidate.setObjectName(_fromUtf8("btnValidate"))
        self.horizontalLayout_14.addWidget(self.btnValidate)
        self.btnCancel = QtGui.QPushButton(self.dwc_individu)
        self.btnCancel.setEnabled(False)
        self.btnCancel.setMinimumSize(QtCore.QSize(60, 30))
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.horizontalLayout_14.addWidget(self.btnCancel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        individu_form.setWidget(self.dwc_individu)

        self.retranslateUi(individu_form)
        self.tab_infos.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(individu_form)

    def retranslateUi(self, individu_form):
        individu_form.setWindowTitle(_translate("individu_form", "Geolimi - Individu et observation", None))
        self.chkFiltreIndividu.setText(_translate("individu_form", "filtre individu", None))
        self.btnFiltreAttributaire.setToolTip(_translate("individu_form", "Filtre des observations", None))
        self.btnFiltreAttributaire.setText(_translate("individu_form", "Filtre attributaire", None))
        self.btnDeleteFiltrage.setToolTip(_translate("individu_form", "Enlever le filtre actuel", None))
        self.btnDeleteFiltrage.setText(_translate("individu_form", "Suppression filtrage", None))
        self.label.setText(_translate("individu_form", "Id", None))
        self.chk_ind_actif.setText(_translate("individu_form", "Actif", None))
        self.label_7.setText(_translate("individu_form", "Logger", None))
        self.label_8.setText(_translate("individu_form", "Espèce", None))
        self.btnGereEspece.setToolTip(_translate("individu_form", "Gestion des indices de répétition", None))
        self.btnGereEspece.setText(_translate("individu_form", "...", None))
        self.label_9.setText(_translate("individu_form", "Age", None))
        self.btnGereAge.setToolTip(_translate("individu_form", "Gestion des indices de répétition", None))
        self.btnGereAge.setText(_translate("individu_form", "...", None))
        self.chk_ind_sexe_m.setText(_translate("individu_form", "Sexe mâle", None))
        self.chk_ind_sexe_verifie.setText(_translate("individu_form", "Sexe vérifié", None))
        self.label_10.setText(_translate("individu_form", "District", None))
        self.btnGereDistrict.setToolTip(_translate("individu_form", "Gestion des indices de répétition", None))
        self.btnGereDistrict.setText(_translate("individu_form", "...", None))
        self.label_5.setText(_translate("individu_form", "Date de capture", None))
        self.label_6.setText(_translate("individu_form", "N° bague", None))
        self.label_11.setText(_translate("individu_form", "Code gauche", None))
        self.label_12.setText(_translate("individu_form", "Code droit", None))
        self.label_18.setText(_translate("individu_form", "Mesures", None))
        self.label_25.setText(_translate("individu_form", "Aile", None))
        self.label_26.setText(_translate("individu_form", "Bec", None))
        self.label_27.setText(_translate("individu_form", "Tarse", None))
        self.label_28.setText(_translate("individu_form", "Masse", None))
        self.btnAddObservation.setToolTip(_translate("individu_form", "Ajout d\'une observation", None))
        self.btnDeleteObservation.setToolTip(_translate("individu_form", "Suppression d\'une observation", None))
        self.btnEditObservation.setToolTip(_translate("individu_form", "Modification d\'une observation", None))
        self.btnCentrer.setToolTip(_translate("individu_form", "Centrer sur l\'observation", None))
        self.btnZoomer.setToolTip(_translate("individu_form", "Zoomer sur l\'observation", None))
        self.btnSelectionner.setToolTip(_translate("individu_form", "Sélectionner l\'observation", None))
        self.btnZoomerSelectionner.setToolTip(_translate("individu_form", "Zoomer sur l\'observation et sélectionner", None))
        self.tab_infos.setTabText(self.tab_infos.indexOf(self.tab_observation), _translate("individu_form", "Observations", None))
        self.btnAddAncienLogger.setToolTip(_translate("individu_form", "Ajout d\'un travail effectué", None))
        self.btnDeleteAncienLogger.setToolTip(_translate("individu_form", "Suppression d\'un travail effectué", None))
        self.tab_infos.setTabText(self.tab_infos.indexOf(self.tab_logger), _translate("individu_form", "Anciens loggers", None))
        self.btnFirst.setToolTip(_translate("individu_form", "Revenir au premier individu", None))
        self.btnPrev.setToolTip(_translate("individu_form", "Passer à l\'individu précédent", None))
        self.btnNext.setToolTip(_translate("individu_form", "Passer à l\'individu suivant", None))
        self.btnLast.setToolTip(_translate("individu_form", "Aller au dernier individu", None))
        self.btnAdd.setToolTip(_translate("individu_form", "Ajouter un individu", None))
        self.btnAdd.setText(_translate("individu_form", "Ajout", None))
        self.btnDelete.setToolTip(_translate("individu_form", "Supprimer un individu", None))
        self.btnDelete.setText(_translate("individu_form", "Suppression", None))
        self.btnValidate.setToolTip(_translate("individu_form", "Valider l\'action", None))
        self.btnValidate.setText(_translate("individu_form", "Validation", None))
        self.btnCancel.setToolTip(_translate("individu_form", "Annuler l\'action", None))
        self.btnCancel.setText(_translate("individu_form", "Abandon", None))

import resourcesGeolimi_rc
